version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            CAPE_DEPENDENCIES=True pip3 install --upgrade git+https://github.com/bloomsburyai/cape-splitter

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --pyargs cape_splitter.tests --junitxml=test-results.xml

      - store_test_results:
          path: test-results.xml

      - store_artifacts:
          path: test-results.xml